name: lipophilicity-prediction36
channels:
  - rdkit
  - anaconda
  - defaults
dependencies:
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2021.5.25
  - cairo=1.16.0
  - certifi=2020.12.5
  - cffi=1.14.5
  - cudatoolkit=9.0
  - fontconfig=2.13.1
  - freetype=2.10.4
  - gettext=0.21.0
  - glib=2.68.2
  - icu=58.2
  - intel-openmp=2021.2.0
  - joblib=1.0.1
  - jpeg=9b
  - lcms2=2.12
  - libboost=1.73.0
  - libffi=3.3
  - libpng=1.6.37
  - libtiff=4.2.0
  - libwebp-base=1.2.0
  - libxml2=2.9.10
  - lz4-c=1.9.3
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.0.4
  - ncurses=6.2
  - ninja=1.10.2
  - numpy=1.17.0
  - numpy-base=1.17.0
  - olefile=0.46
  - openssl=1.1.1k
  - pandas=1.1.5
  - pcre=8.44
  - pillow=8.2.0
  - pip=21.1.1
  - pixman=0.40.0
  - py-boost=1.73.0
  - pycparser=2.20
  - python=3.6.13
  - python-dateutil=2.8.1
  - pytorch=1.4.0
  - pytz=2021.1
  - rdkit=2020.09.1.0
  - readline=8.1
  - scikit-learn=0.24.2
  - scipy=1.5.2
  - setuptools=52.0.0
  - six=1.15.0
  - sqlite=3.35.4
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - tqdm=4.59.0
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - aiocontextvars==0.2.2
    - contextvars==2.4
    - immutables==0.15
    - loguru==0.5.3
    - mypy-extensions==0.4.3
    - pandas-flavor==0.2.0
    - typed-argument-parser==1.6.2
    - typing-extensions==3.10.0.0
    - typing-inspect==0.6.0
    - xarray==0.16.2
