file_prefix: logd_Lip_wo_averaging
split_file_prefix: logd_Lip_wo_averaging
input_path: ./data/3_final_data/split_data
save_dir: ./data/raw/baselines/dmpnn/logs/exp_0
epochs: 100
patience: 1000
delta: 0.001
depth: 6
features_generator: [rdkit_wo_fragments_and_counts]
no_features_scaling: True
target_columns: [logD]
split_type: k-fold
num_folds: 4
data_path: ./data/raw/baselines/dmpnn/
additional_encoder: True
separate_test_path: ./data/3_final_data/split_data
substructures_hidden_size: 300
hidden_size: 800
